### ISSUE TITLE
Error: Cannot find module 'nan'

### ISSUE THREAD

**Issue by lanodan** [handshake-org/hs-miner#5]
As you can see hs-miner fails to build.

```
$ make

> hs-miner@0.0.2 install-main /seagate/sources/git/github.com/handshake-org/hs-miner
> ./scripts/rebuild main

++ test -z ''
++ echo g++
+ CXX=g++
++ ./scripts/get endian
+ ENDIAN=little
++ ./scripts/get cuda_has
+ CUDA_HAS=0
++ ./scripts/get nvcc
+ NVCC=/opt/cuda/bin/nvcc
++ ./scripts/get bits
+ BITS=29
++ ./scripts/get size
+ SIZE=42
++ ./scripts/get perc
+ PERC=50
++ ./scripts/get network
+ NETWORK=main
++ test little = little
++ echo -DHS_LITTLE_ENDIAN
+ DENDIAN=-DHS_LITTLE_ENDIAN
+ test 0 -eq 1
+ rm -f src/device.a
+ rm -f src/mean-cuda.a
+ rm -f src/lean-cuda.a
+ node-gyp rebuild
module.js:487
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:569:30)
    at evalScript (bootstrap_node.js:432:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.14.47-gentoo
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /seagate/sources/git/github.com/handshake-org/hs-miner
gyp ERR! node -v v8.1.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hs-miner@0.0.2 install-main: `./scripts/rebuild main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hs-miner@0.0.2 install-main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/haelwenn/.npm/_logs/2018-08-06T15_29_53_598Z-debug.log

make: *** [Makefile:2: all] Fehler 1
```

```
$ node --version
v8.1.1
$ npm --version
5.0.3
```

* [/home/haelwenn/.npm/_logs/2018-08-06T15_29_53_598Z-debug.log](https://github.com/handshake-org/hs-miner/files/2263123/2018-08-06T15_29_53_598Z-debug.log)

**Comment by chris13524** [comment]
Yup, same issue here. Any solution?

**Comment by lanodan** [comment]
It’s probably lacking something like ``npm install`` in the installation.
I quickly glanced at ``package.json`` and nan is in it.

**Comment by boymanjor** [comment]
`npm install` is listed in the install instructions. Closing this now.
